/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.tiger.useragent;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserAgentInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserAgentInfo\",\"namespace\":\"com.tiger.useragent\",\"fields\":[{\"name\":\"os_name\",\"type\":\"string\",\"default\":\"-\"},{\"name\":\"os\",\"type\":\"string\",\"default\":\"-\"},{\"name\":\"browser_name\",\"type\":\"string\",\"default\":\"-\"},{\"name\":\"browser\",\"type\":\"string\",\"default\":\"-\"},{\"name\":\"device_brand\",\"type\":\"string\",\"default\":\"-\"},{\"name\":\"device_name\",\"type\":\"string\",\"default\":\"-\"},{\"name\":\"device_type\",\"type\":\"string\",\"default\":\"-\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Deprecated public java.lang.CharSequence os_name;
  @Deprecated public java.lang.CharSequence os;
  @Deprecated public java.lang.CharSequence browser_name;
  @Deprecated public java.lang.CharSequence browser;
  @Deprecated public java.lang.CharSequence device_brand;
  @Deprecated public java.lang.CharSequence device_name;
  @Deprecated public java.lang.CharSequence device_type;
  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public UserAgentInfo() {}

  /**
   * All-args constructor.
   */
  public UserAgentInfo(java.lang.CharSequence os, java.lang.CharSequence os_name, java.lang.CharSequence browser, java.lang.CharSequence browser_name, java.lang.CharSequence device_brand, java.lang.CharSequence device_name, java.lang.CharSequence device_type) {
    this.os_name = os_name;
    this.os = os;
    this.browser_name = browser_name;
    this.browser = browser;
    this.device_brand = device_brand;
    this.device_name = device_name;
    this.device_type = device_type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return os_name;
    case 1: return os;
    case 2: return browser_name;
    case 3: return browser;
    case 4: return device_brand;
    case 5: return device_name;
    case 6: return device_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: os_name = (java.lang.CharSequence)value$; break;
    case 1: os = (java.lang.CharSequence)value$; break;
    case 2: browser_name = (java.lang.CharSequence)value$; break;
    case 3: browser = (java.lang.CharSequence)value$; break;
    case 4: device_brand = (java.lang.CharSequence)value$; break;
    case 5: device_name = (java.lang.CharSequence)value$; break;
    case 6: device_type = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'os_name' field.
   */
  public java.lang.CharSequence getOsName() {
    return os_name;
  }

  /**
   * Sets the value of the 'os_name' field.
   * @param value the value to set.
   */
  public void setOsName(java.lang.CharSequence value) {
    this.os_name = value;
  }

  /**
   * Gets the value of the 'os_detail' field.
   */
  public java.lang.CharSequence getOs() {
    return os;
  }

  /**
   * Sets the value of the 'os_detail' field.
   * @param value the value to set.
   */
  public void setOs(java.lang.CharSequence value) {
    this.os = value;
  }

  /**
   * Gets the value of the 'browser_name' field.
   */
  public java.lang.CharSequence getBrowserName() {
    return browser_name;
  }

  /**
   * Sets the value of the 'browser_name' field.
   * @param value the value to set.
   */
  public void setBrowserName(java.lang.CharSequence value) {
    this.browser_name = value;
  }

  /**
   * Gets the value of the 'browser_detail' field.
   */
  public java.lang.CharSequence getBrowser() {
    return browser;
  }

  /**
   * Sets the value of the 'browser_detail' field.
   * @param value the value to set.
   */
  public void setBrowser(java.lang.CharSequence value) {
    this.browser = value;
  }

  /**
   * Gets the value of the 'device_brand' field.
   */
  public java.lang.CharSequence getDeviceBrand() {
    return device_brand;
  }

  /**
   * Sets the value of the 'device_brand' field.
   * @param value the value to set.
   */
  public void setDeviceBrand(java.lang.CharSequence value) {
    this.device_brand = value;
  }

  /**
   * Gets the value of the 'device_name' field.
   */
  public java.lang.CharSequence getDeviceName() {
    return device_name;
  }

  /**
   * Sets the value of the 'device_name' field.
   * @param value the value to set.
   */
  public void setDeviceName(java.lang.CharSequence value) {
    this.device_name = value;
  }

  /**
   * Gets the value of the 'device_type' field.
   */
  public java.lang.CharSequence getDeviceType() {
    return device_type;
  }

  /**
   * Sets the value of the 'device_type' field.
   * @param value the value to set.
   */
  public void setDeviceType(java.lang.CharSequence value) {
    this.device_type = value;
  }

  /**
   * Creates a new UserAgentInfo RecordBuilder.
   * @return A new UserAgentInfo RecordBuilder
   */
  public static com.tiger.useragent.UserAgentInfo.Builder newBuilder() {
    return new com.tiger.useragent.UserAgentInfo.Builder();
  }
  
  /**
   * Creates a new UserAgentInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserAgentInfo RecordBuilder
   */
  public static com.tiger.useragent.UserAgentInfo.Builder newBuilder(com.tiger.useragent.UserAgentInfo.Builder other) {
    return new com.tiger.useragent.UserAgentInfo.Builder(other);
  }
  
  /**
   * Creates a new UserAgentInfo RecordBuilder by copying an existing UserAgentInfo instance.
   * @param other The existing instance to copy.
   * @return A new UserAgentInfo RecordBuilder
   */
  public static com.tiger.useragent.UserAgentInfo.Builder newBuilder(com.tiger.useragent.UserAgentInfo other) {
    return new com.tiger.useragent.UserAgentInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for UserAgentInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserAgentInfo>
    implements org.apache.avro.data.RecordBuilder<UserAgentInfo> {

    private java.lang.CharSequence os_name;
    private java.lang.CharSequence os;
    private java.lang.CharSequence browser_name;
    private java.lang.CharSequence browser;
    private java.lang.CharSequence device_brand;
    private java.lang.CharSequence device_name;
    private java.lang.CharSequence device_type;

    /** Creates a new Builder */
    private Builder() {
      super(com.tiger.useragent.UserAgentInfo.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tiger.useragent.UserAgentInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.os_name)) {
        this.os_name = data().deepCopy(fields()[0].schema(), other.os_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.os)) {
        this.os = data().deepCopy(fields()[1].schema(), other.os);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.browser_name)) {
        this.browser_name = data().deepCopy(fields()[2].schema(), other.browser_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.browser)) {
        this.browser = data().deepCopy(fields()[3].schema(), other.browser);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.device_brand)) {
        this.device_brand = data().deepCopy(fields()[4].schema(), other.device_brand);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.device_name)) {
        this.device_name = data().deepCopy(fields()[5].schema(), other.device_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.device_type)) {
        this.device_type = data().deepCopy(fields()[6].schema(), other.device_type);
        fieldSetFlags()[6] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing UserAgentInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tiger.useragent.UserAgentInfo other) {
      super(com.tiger.useragent.UserAgentInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.os_name)) {
        this.os_name = data().deepCopy(fields()[0].schema(), other.os_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.os)) {
        this.os = data().deepCopy(fields()[1].schema(), other.os);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.browser_name)) {
        this.browser_name = data().deepCopy(fields()[2].schema(), other.browser_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.browser)) {
        this.browser = data().deepCopy(fields()[3].schema(), other.browser);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.device_brand)) {
        this.device_brand = data().deepCopy(fields()[4].schema(), other.device_brand);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.device_name)) {
        this.device_name = data().deepCopy(fields()[5].schema(), other.device_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.device_type)) {
        this.device_type = data().deepCopy(fields()[6].schema(), other.device_type);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'os_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getOsName() {
      return os_name;
    }

    /**
      * Sets the value of the 'os_name' field.
      * @param value The value of 'os_name'.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder setOsName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.os_name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'os_name' field has been set.
      * @return True if the 'os_name' field has been set, false otherwise.
      */
    public boolean hasOsName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'os_name' field.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder clearOsName() {
      os_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'os' field.
      * @return The value.
      */
    public java.lang.CharSequence getOs() {
      return os;
    }

    /**
      * Sets the value of the 'os' field.
      * @param value The value of 'os'.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder setOs(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.os = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'os' field has been set.
      * @return True if the 'os' field has been set, false otherwise.
      */
    public boolean hasOs() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'os' field.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder clearOs() {
      os = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'browser_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrowserName() {
      return browser_name;
    }

    /**
      * Sets the value of the 'browser_name' field.
      * @param value The value of 'browser_name'.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder setBrowserName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.browser_name = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'browser_name' field has been set.
      * @return True if the 'browser_name' field has been set, false otherwise.
      */
    public boolean hasBrowserName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'browser_name' field.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder clearBrowserName() {
      browser_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'browser' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrowser() {
      return browser;
    }

    /**
      * Sets the value of the 'browser' field.
      * @param value The value of 'browser_'.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder setBrowser(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.browser = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'browser' field has been set.
      * @return True if the 'browser' field has been set, false otherwise.
      */
    public boolean hasBrowser() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'browser' field.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder clearBrowser() {
      browser = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_brand' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceBrand() {
      return device_brand;
    }

    /**
      * Sets the value of the 'device_brand' field.
      * @param value The value of 'device_brand'.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder setDeviceBrand(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.device_brand = value;
      fieldSetFlags()[4] = true;
      return this; 
    }

    /**
      * Checks whether the 'device_brand' field has been set.
      * @return True if the 'device_brand' field has been set, false otherwise.
      */
    public boolean hasDeviceBrand() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'device_brand' field.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder clearDeviceBrand() {
      device_brand = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceName() {
      return device_name;
    }

    /**
      * Sets the value of the 'device_name' field.
      * @param value The value of 'device_name'.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder setDeviceName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.device_name = value;
      fieldSetFlags()[5] = true;
      return this; 
    }

    /**
      * Checks whether the 'device_name' field has been set.
      * @return True if the 'device_name' field has been set, false otherwise.
      */
    public boolean hasDeviceName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'device_name' field.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder clearDeviceName() {
      device_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceType() {
      return device_type;
    }

    /**
      * Sets the value of the 'device_type' field.
      * @param value The value of 'device_type'.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder setDeviceType(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.device_type = value;
      fieldSetFlags()[6] = true;
      return this; 
    }

    /**
      * Checks whether the 'device_type' field has been set.
      * @return True if the 'device_type' field has been set, false otherwise.
      */
    public boolean hasDeviceType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'device_type' field.
      * @return This builder.
      */
    public com.tiger.useragent.UserAgentInfo.Builder clearDeviceType() {
      device_type = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public UserAgentInfo build() {
      try {
        UserAgentInfo record = new UserAgentInfo();
        record.os_name = fieldSetFlags()[0] ? this.os_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.os = fieldSetFlags()[1] ? this.os : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.browser_name = fieldSetFlags()[2] ? this.browser_name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.browser = fieldSetFlags()[3] ? this.browser : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.device_brand = fieldSetFlags()[4] ? this.device_brand : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.device_name = fieldSetFlags()[5] ? this.device_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.device_type = fieldSetFlags()[6] ? this.device_type : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
